SHOW DATABASES;
CREATE DATABASE H32_BLOG;
SHOW DATABASES;
USE H32_BLOG;
CREATE TABLE USER (
	userID INT PRIMARY KEY AUTO_INCREMENT,
	accountName VARCHAR(50) NOT NULL UNIQUE,
    passWord VARCHAR(50) NOT NULL,
    birthdayDatetime  DATETIME  DEFAULT CURRENT_TIMESTAMP,
	address NVARCHAR(100) DEFAULT 'H32_LAB',
    phoneNumber VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    about VARCHAR(500) NOT NULL UNIQUE,
    insLink TEXT,
    faceLink TEXT,
    major NVARCHAR(500)
);

CREATE TABLE USERROLE (
	userRoleID VARCHAR(50) PRIMARY KEY,
	userRoleNote VARCHAR(50),
    active BOOLEAN NOT NULL,
    createByUserID INT
);

CREATE TABLE USERUSERROLE (
	userID INT,
    userRoleID VARCHAR(50),
    PRIMARY KEY (userID, userRoleID),
    FOREIGN KEY (userID) REFERENCES USER(userID),
    FOREIGN KEY (userRoleID) REFERENCES USERROLE(userRoleID)
);

CREATE TABLE IMAGEUSER (
	imageID VARCHAR(50) PRIMARY KEY,
	userID INT NOT NULL,
    imgURL TEXT NOT NULL,
    FOREIGN KEY (userID) REFERENCES USER(userID)
);

CREATE TABLE LabImage (
	labImageID VARCHAR(50) PRIMARY KEY,
    userID INT NOT NULL,
    tag VARCHAR(50) NOT NULL,
    description NVARCHAR(100) DEFAULT "img_lab",
    year DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES USER(userID)
);

CREATE TABLE TimeLine (
	timeLineID INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    tag VARCHAR(50) NOT NULL,
    description NVARCHAR(200) NOT NULL,
    year DATETIME DEFAULT CURRENT_TIMESTAMP,
    title NVARCHAR(50) NOT NULL
);
